# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker:20.10.9  # Specify the Docker version you needx
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
        NODE_ENV: development
      ports:
        - 7635
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t data-primals-engine . -f DockerfileTest

    - name: Run Docker container
      run: |
        docker run -p 7635:7635 -d --name data-container data-primals-engine

    - name: Run tests
      run: |
        docker exec data-container npm run test
